import Head from "next/head";
import Auth from "@/components/Auth";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-purple-600">
        <h1>hello</h1>
        <Auth />
      </main>
    </div>
  );
}
